version: '3.8'
services:
    node:    
      image: 'node:14-alpine'
      volumes:
        - "./:/home/node/app"
      working_dir: '/home/node/app'
      command: /bin/sh -c "npm install && npm start"